# File: nixpacks.toml

[phases.setup]
# Menambahkan paket-paket PHP yang kita butuhkan
# pkgs = ["php", "php-pdo", "php-pdo_mysql", "php-bcmath"]
# Update: Nixpacks versi baru lebih suka format ini:
pkgs = ["php", "phpExtensions.pdo_mysql", "phpExtensions.bcmath"]

[start]
# Kamu bisa juga letakkan start command di sini, 
# tapi lebih baik biarkan di dashboard Railway agar mudah diubah.
# cmd = "sleep 10 && php artisan config:cache && php artisan migrate:refresh --force && php artisan serve --host 0.0.0.0 --port $PORT"